Citizen.CreateThread(function()
	-- ACURA
	AddTextEntry('sunrise1', 'Maibatsu Sunrise R')
	AddTextEntry('buffalo4h', 'Vapid Buffalo Hellcat')
	AddTextEntry('gauntletctx', 'Gauntlet Hellfire')
	AddTextEntry('zr390', 'Annis ZR390')
	AddTextEntry('sunrise1', 'Maibatsu Sunrise R')
	AddTextEntry('mesaxl', 'Canis Gator')
	AddTextEntry('mesar', 'Canis Mesa')
	AddTextEntry('r9gt', 'Dewbauchee R9GT')
	AddTextEntry('schlagenstr', 'Gauntlet STX')
	AddTextEntry('hizoku', 'Annis Hizoku')
	AddTextEntry('coquette4c', 'Invetero Coquette')
	AddTextEntry('lynxgpr', 'Lynx GPR')
	AddTextEntry('schlagenstr', 'Benefactor Schlagen STR')
	AddTextEntry('sentineldm', 'Sentinel DM')
	AddTextEntry('sultan2c', 'Sultan Custom Classic')
	AddTextEntry('fuknking', 'Vapid XL')
	AddTextEntry('sombrero', 'Western Sombrero')

end)